# Generated by Django 5.0.6 on 2024-05-16 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listas',
            name='usuarios',
        ),
    ]
