# Generated by Django 5.0.6 on 2024-05-16 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0002_remove_listas_usuarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listas',
            old_name='discricao',
            new_name='descricao',
        ),
    ]
